trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  displayName: 'Install Node.js'
  inputs:
    version: '16.x'

- script: |
    npm install
  displayName: 'NpmInstall'

- script: |
    npm run build
  displayName: 'NpmBuild'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: AngularLogin
    targetPath: '$(Build.SourcesDirectory)/dist'
    publishLocation: 'pipeline'
  displayName: 'PublishNpmArtifact'

- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    WebSiteName: 'AngularLogin'
    VirtualApplication: 'http://172.16.0.245:145/AngularLogin'
    Package: '$(Build.SourcesDirectory)/dist'