trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  displayName: 'Install Node.js'
  inputs:
    version: '16.x'

- script: |
    npm install
  displayName: 'NpmInstall'

- script: |
    npm run build
  displayName: 'NpmBuild'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: AngularLogin
    targetPath: '$(Build.SourcesDirectory)/dist'
    publishLocation: 'pipeline'
  displayName: 'PublishNpmArtifact'

- script: |
    # Example script to deploy using msdeploy command
    mono C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe -verb:sync -source:package='$(Build.SourcesDirectory)/dist' -dest:auto,ComputerName='https://172.16.0.245:145/MSDeployAgentService',UserName='admin',Password='Admin@123',AuthType='Basic' -setParam:name='AngularLogin',value='AngularLogin' -allowUntrusted
  displayName: 'Deploy to IIS'